name: Wilson Test Runner
description: Parallel test runner
author: SjorsO

branding:
  icon: wind
  color: purple

inputs:
  url:
    description: Url to Wilson
    required: true
  api_key:
    description: Your Wilson API key
    required: true
  type:
    description: The type of the run (either "phpunit" or "dusk")
    required: true
  swarm:
    description: Name of the swarm
    required: true
  bundle:
    description: Application bundle file path
    required: true
    default: '~/wilson-bundle.tar.gz'

#outputs:
#  time:
#    description: Your output description here

runs:
  using: node20
  main: dist/index.js
