name: Wilson Test Runner
description: Parallel test runner
author: SjorsO

branding:
  icon: wind
  color: purple

inputs:
  url:
    description: Url to Wilson
    required: true
  api_key:
    description: Your Wilson API key
    required: true
  config:
    description: Name of your Wilson file
    required: true
    default: 'wilson'
  bundle:
    description: Application bundle file path
    required: true
    default: '~/wilson-bundle.tar.gz'

#outputs:
#  time:
#    description: Your output description here

runs:
  using: node20
  main: dist/index.js
