name: Tag Latest Commit
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  tag-latest-commit:
    runs-on: "ubuntu-22.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            await github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/dev',
            });
            
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/dev',
              sha: context.sha
            })
